### PR TITLE
Add Stress Tests

### PR DESCRIPTION
**Pull request by geeklostinwoods**
1. Create multiple files sequential to validate if create api creates
   multiple files realiably.
2. Create Multiple Files Parallely to validate if create api creates
   multiple files realiably.

### CODE REVIEW

**Comment by carl-woodward-mcafee** [comment]
Hi @geeklostinwoods, I hope all is well! Many thanks for submitting your coding test. Unfortunately, I can't accept a PR because this would give other candidates the opportunity to review your answer. But, I will pull the source, review your submission, and then delete the PR/branch.

Thank you again!

**Comment by geeklostinwoods** [comment]
Thanks.

Yes i just wanted you to see changes.

Even though i worked in wdf team, i never worked on writing driver. I
worked on usb layer and specially usb hid and lot of work with beagle
device sniffing usb traffic. Mostly manual and semi automated tools.

I did work on one windbg extension and a partial driver where i just made
few fixes. I learnt basics of kmdf, wdf.  But i am still very beginner in
driver programming.

I though very much love this area. If i could recieve some training and
help, i would love to learn more and i can work as contract for lowest
price like 40$ or 50$ an hour because i really want to learn this area. I
am citizen so could work on 1099 as well.

I worked in room systems and few other usb hid layer , mostly from
applications side consuming hid reports from the driver but its mostly
firmware and uses inbox usb drivers and hid protocol.

Thanks
Ram

**Comment by carl-woodward-mcafee** [comment]
Hi Ram,

I hope all is well!

We have an interview scheduled for now, but the meeting hasn't been started for us. Are you available for the interview still? If so, I'll make a new meeting.

Many thanks!


[1507310492665_PastedImage]
Carl Woodward
Office of the CTO
@carl_woodward
D: 408.802.0616   M: 408.802.0616



The information contained in this email message may be privileged, confidential and protected from disclosure. If you are not the intended recipient, any review, dissemination, distribution or copying is strictly prohibited. If you have received this email message in error, please notify the sender by reply email and delete the message and any attachments.


________________________________

**Comment by geeklostinwoods** [comment]
Oh i didnt get any invite? Can we do tomorrow? I am out for lunch now.

**Comment by carl-woodward-mcafee** [comment]
Hi Ram,

Apologies I missed your email! That explains what happened!

Vinita will arrange a new interview, and we can chat then. Very much looking forward to it!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
